apiVersion: v1
kind: Pod
metadata:
        name: ubuntu
        labels:
                app: ubuntu
spec:
        hostname: ubuntu
        containers:
                - name: ubuntu
                  image: ubuntu:latest
                  command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
