apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-pv-claim
  labels:
    app: ubuntu
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  hostname: ubuntu
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
    volumeMounts:
    - name: ubuntu-persistent-storage
      mountPath: /data
  volumes:
  - name: ubuntu-persistent-storage
    persistentVolumeClaim:
      claimName: ubuntu-pv-claim
