---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-volume
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
