---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: scollector
  labels:
    app: scollector
spec:
  selector:
    matchLabels:
      name: scollector 
  template:
    metadata:
      labels:
        name: scollector
    spec:
      hostNetwork: true
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
        - name: scollector
          #image: rohit01/scollector
          image: sylvaintremblay/scollector-multiarch
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
          - name: "SC_CONF_Host"
            #value: "opentsdb-opentsdb:4242"
            value: "localhost:30666"
            #      - name: "HOSTNAME"
            #        valueFrom:
            #          fieldRef:
            #            fieldPath: spec.nodeName
