apiVersion: v1
kind: Service
metadata:
  name: opentsdb-external
spec:
  selector:
    app.kubernetes.io/name: opentsdb
  type: NodePort
  ports:
    - protocol: TCP
      port: 4242
      nodePort: 30666

