---
apiVersion: v1
kind: Pod
metadata:
  name: plex
  labels:
    app: plex
spec:
  volumes:
    - name: multimedia-nfs
      hostPath: 
        path: /multimedia
    - name: plex-metadata-storage
      persistentVolumeClaim:
        claimName: plex-metadata
  hostNetwork: true
  containers:
    - name: plex
      image: plexinc/pms-docker
      imagePullPolicy: Always
      env:
      - name: TZ
        value: "America/Montreal"
#      - name: PLEX_CLAIM
#        value: "claim-ZX7x1wfsussSR5U7NC8Y"
      resources:
        requests:
          memory: 1Gi
          cpu: 1000m
        limits:
          memory: 4Gi
          cpu: 10000m
      volumeMounts:
        - mountPath: "/multimedia"
          name: multimedia-nfs
        - mountPath: "/config"
          name: plex-metadata-storage
#  nodeSelector:
#    kubernetes.io/hostname: x3650
