---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-hbase-zookeeper-0
  labels:
    app: zookeeper
    zomponent: server
    release: hbase
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
